
def server = Artifactory.server('jfrog')
pipeline {
agent any
 stages{
	stage('Build') {  
      
      steps {               
             bat'compile'
   		     echo 'Building..'           
           }        
      }     
      stage('Test') {          
        steps {       
        	bat'make check || true'
        	bat'test'
            echo 'Testing..'           
           }        
       }       
       stage('Deploy') {    
       	 when{              
	        expression {
	                  currentBuild.result == null || currentBuild.result == 'SUCCESS'
	                 }
	         }         
           steps {               
            echo 'Deploying....'
            bat'install'
        }  
      }
       stage('My stage') {           
           steps {               
            echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}" 
            echo 'My stage....'           
        }     
    }
      stage('END') {           
           steps {              
            echo 'Built....'           
        }  
    }
  }
}
 

 