
def server = Artifactory.server('jfrog')
def buildInfo = Artifactory.newBuildInfo()
def uploadSpec = """{
  "files": [
    {
      "pattern": "my-app/target/**.jar",
      "target": "Jenkins-integration/"
    }
 ]
}"""

pipeline {
agent any
 stages{
	stage('Build') {  
      steps {      
       		 echo 'Building..'           
             bat'compile'
           }        
      }     
      stage('Test') {          
        steps {     
            echo 'Testing..'  
        	bat'make check || true'
        	bat'test'
           }        
       }       
       stage('Deploy') {    
       	 when{              
	        expression {
	                  currentBuild.result == null || currentBuild.result == 'SUCCESS'
	                 }
	         }         
           steps {               
            echo 'Deploying....'
            bat'install'
        }  
      }
       stage('My stage') {        
           options {
                timeout(time: 1, unit: 'HOURS') 
           }   
           steps {       
            echo 'My stage....'              
            echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}" 
                
        }     
    }
      stage('END') {
           steps {
         	 echo 'Hello Artifactory'
         	  bat'deploy'
         	 script{
         	 	buildInfo.env.capture = true
         		server.upload(uploadSpec)
         		echo buildInfo.name
         		echo buildInfo.number
         		server.publishBuildInfo(buildInfo)
         	 }
        }  //
    }
  }
}
 