
pipeline {
agent any
 stages{
	stage('Build') {  
      
      steps {               
          //   bat'make'
            // bat "mvn -f C:/Users/h239267/git/broken/com.vogella.dnd.jface1/pom.xml compile  "
   		     echo 'Building..'           
           }       
      }     
      stage('Test') {          
        steps {       
        	 bat'make check || true'
			// junit '**/target/*.xml' 
            echo 'Testing..'           
           }        
       }       
       stage('Deploy') {    
       	 when{              
	        expression {
	                  //  currentBuild.result != null || currentBuild.result == 'SUCCESS'
	                  currentBuild.result == null || currentBuild.result == 'SUCCESS'
	                 }
	         }         
           steps {     //           
           // echo 'Deploying....'
            rtServer (
    id: 'jfrog',
    url: 'http://localhost:82/artifactory',
    username: 'jenkins',
    password: 'Ufoper66',
    bypassProxy: true,
    timeout = 300
)
        }  
      }
       stage('My stage') {           
           steps {               
            echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}" 
            echo 'My stage....'           
        }     
    }
      stage('END') {           
           steps {               
            echo 'Built....'           
        }  
    }
  }
}
 

 